# Generated by Django 4.1.7 on 2023-04-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='placement',
            field=models.CharField(blank=True, default='A', help_text='Place on the home page (A, B, C, etc..)', max_length=20, verbose_name='placement'),
        ),
    ]
