# Generated by Django 4.1.7 on 2023-04-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='place_number',
            field=models.IntegerField(default=0, help_text='A number to help determine where posts of this placement appear the template.'),
            preserve_default=False,
        ),
    ]
