# Generated by Django 4.1.7 on 2023-04-08 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0002_post_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the region where this post will be placed', max_length=20, verbose_name='name')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='placement',
            field=models.ForeignKey(blank=True, help_text='The place on the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdchomepage.placement'),
        ),
    ]
