# Generated by Django 4.1.7 on 2023-04-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tougblog', '0002_placement_place_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placement',
            options={'ordering': ('place_number',)},
        ),
    ]
