# Generated by Django 4.1.7 on 2023-04-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0003_placement_alter_post_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='name',
        ),
        migrations.AddField(
            model_name='placement',
            name='place',
            field=models.CharField(blank=True, help_text='The single letter of the place on the template that corresponds to', max_length=1, verbose_name='place'),
        ),
        migrations.AddField(
            model_name='placement',
            name='title',
            field=models.CharField(blank=True, help_text='The title to be displayed for this placement', max_length=20, verbose_name='title'),
        ),
    ]
