# Generated by Django 4.1.7 on 2023-04-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tougblog', '0003_alter_placement_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='list_order',
        ),
    ]
