# Generated by Django 4.1.7 on 2023-04-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougblog', '0004_remove_placement_list_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='draft_status',
            field=models.IntegerField(choices=[('published', 7), ('draft', 0)], default=0, help_text='If this post is a draft, which only displays in preview mode', verbose_name='draft status'),
        ),
        migrations.AddField(
            model_name='page',
            name='draft_status',
            field=models.IntegerField(choices=[('published', 7), ('draft', 0)], default=0, help_text='If this post is a draft, which only displays in preview mode', verbose_name='draft status'),
        ),
        migrations.AddField(
            model_name='post',
            name='draft_status',
            field=models.IntegerField(choices=[('published', 7), ('draft', 0)], default=0, help_text='If this post is a draft, which only displays in preview mode', verbose_name='draft status'),
        ),
    ]
