# Generated by Django 4.1.7 on 2023-04-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0004_remove_placement_name_placement_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, help_text='A shorter version of the content', verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='The content of the post', verbose_name='content'),
        ),
    ]
