# Generated by Django 4.1.7 on 2023-04-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0005_post_summary_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='list_order',
            field=models.CharField(blank=True, default='~', help_text='A character to determine the place on the list. Numbers are higher than capital letters, which are higher than small letters', max_length=1),
        ),
    ]
