# Generated by Django 4.1.7 on 2023-04-12 10:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tougblog', '0005_event_draft_status_page_draft_status_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='draft_status',
            field=models.IntegerField(choices=[('published', 7), ('draft', 0)], default=0, help_text='If this event is a draft, which only displays in preview mode', verbose_name='draft status'),
        ),
        migrations.AlterField(
            model_name='page',
            name='draft_status',
            field=models.IntegerField(choices=[('published', 7), ('draft', 0)], default=0, help_text='If this page is a draft, which only displays in preview mode', verbose_name='draft status'),
        ),
    ]
