# Generated by Django 4.1.7 on 2023-04-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0006_post_list_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('list_order', '-created')},
        ),
        migrations.AddField(
            model_name='post',
            name='content_format',
            field=models.CharField(choices=[('markdown', 'markdown'), ('html', 'html')], default='markdown', help_text='The format (or markup method) used for the content', max_length=20, verbose_name='content format'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_format',
            field=models.CharField(choices=[('same', 'same as content'), ('markdown', 'markdown'), ('html', 'html')], default='same', help_text='The format (or markup method) used for the summary', max_length=20, verbose_name='content format'),
        ),
    ]
