# Generated by Django 4.1.7 on 2023-04-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0008_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the thread', max_length=50, verbose_name='title')),
                ('whenday', models.DateField(help_text='The date of the event', verbose_name='date')),
                ('starttime', models.TimeField(help_text='The start time of the event', verbose_name='starting')),
                ('lenmin', models.IntegerField(help_text='How long the event lasts', verbose_name='length(minutes)')),
                ('content_format', models.CharField(choices=[('markdown', 'markdown'), ('html', 'html')], default='markdown', help_text='The format (or markup method) used for the content', max_length=20, verbose_name='content format')),
                ('content', models.TextField(blank=True, help_text='The content of the post', verbose_name='content')),
                ('summary_format', models.CharField(choices=[('same', 'same as content'), ('markdown', 'markdown'), ('html', 'html')], default='same', help_text='The format (or markup method) used for the summary', max_length=20, verbose_name='content format')),
                ('summary', models.TextField(blank=True, help_text='A shorter version of the content', verbose_name='summary')),
                ('post', models.ForeignKey(blank=True, help_text="The post to use as the content and summary.  If selected, the post content and summary will be used instead of the event's content and summary", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdchomepage.post')),
            ],
            options={
                'ordering': (),
            },
        ),
    ]
