# Generated by Django 4.1.7 on 2023-04-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0009_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lenmin',
            field=models.IntegerField(blank=True, default=0, help_text='How long the event lasts (0 indicates indefinite or unkown)', verbose_name='length(minutes)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starttime',
            field=models.TimeField(blank=True, help_text='The start time of the event', null=True, verbose_name='starting'),
        ),
    ]
