# Generated by Django 4.1.7 on 2023-04-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tougblog', '0010_alter_event_slug_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='The URL of the image. Leave blank to use the Image field. URL will override the image field if URL is not blank', verbose_name='URL')),
                ('slug', models.SlugField(help_text='The slug used to refer to the image in this post (refer to the image with {{ img:my-image }}) if my-image is the slug', verbose_name='slug')),
                ('image', models.ForeignKey(blank=True, help_text='The image included in the post.  Optional if URL is set', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tougblog.image')),
                ('post', models.ForeignKey(help_text='The post which includes the image', on_delete=django.db.models.deletion.CASCADE, to='tougblog.post')),
            ],
        ),
    ]
