# Generated by Django 4.1.7 on 2023-04-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tougblog', '0011_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title_image',
            new_name='list_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_image',
            new_name='list_image',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_image',
        ),
        migrations.AddField(
            model_name='event',
            name='above_content_image',
            field=models.ForeignKey(blank=True, help_text='The image to display above the content, and to use for social media graphs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_above_content_image', to='tougblog.image'),
        ),
        migrations.AddField(
            model_name='event',
            name='below_content_image',
            field=models.ForeignKey(blank=True, help_text='The image to display below the content, and to use for social media graphs if no above_content image is set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_below_content_image', to='tougblog.image'),
        ),
        migrations.AddField(
            model_name='page',
            name='above_content_image',
            field=models.ForeignKey(blank=True, help_text='The image to display above the content, and to use for social media graphs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_above_content_image', to='tougblog.image'),
        ),
        migrations.AddField(
            model_name='page',
            name='below_content_image',
            field=models.ForeignKey(blank=True, help_text='The image to display below the content, and to use for social media graphs if no above_content image is set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_below_content_image', to='tougblog.image'),
        ),
        migrations.AddField(
            model_name='post',
            name='above_content_image',
            field=models.ForeignKey(blank=True, help_text='The image to display above the content, and to use for social media graphs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_above_content_image', to='tougblog.image'),
        ),
        migrations.AddField(
            model_name='post',
            name='below_content_image',
            field=models.ForeignKey(blank=True, help_text='The image to display below the content, and to use for social media graphs if no above_content image is set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_below_content_image', to='tougblog.image'),
        ),
    ]
