# Generated by Django 4.1.7 on 2023-04-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0011_event_title_image_event_title_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.ForeignKey(blank=True, help_text='The image to display above the title, and to use for social media graphs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdchomepage.image'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_image_link',
            field=models.URLField(blank=True, help_text='The link for the image when displayed in single post view', null=True, verbose_name='image link'),
        ),
    ]
