# Generated by Django 4.2 on 2023-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougblog', '0012_rename_title_image_event_list_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='above_content_image_link',
            field=models.URLField(blank=True, help_text='The link for the image displayed above content', verbose_name='above content image link'),
        ),
        migrations.AddField(
            model_name='event',
            name='above_content_target',
            field=models.CharField(blank=True, help_text='The target (ie "_blank" for the link for the image displayed above content', max_length=20, verbose_name='above content target'),
        ),
        migrations.AddField(
            model_name='event',
            name='below_content_image_link',
            field=models.URLField(blank=True, help_text='The link for the image displayed below content', verbose_name='below content image link'),
        ),
        migrations.AddField(
            model_name='event',
            name='below_content_target',
            field=models.CharField(blank=True, help_text='The target (ie "_blank" for the link for the image displayed below content', max_length=20, verbose_name='below content target'),
        ),
        migrations.AddField(
            model_name='page',
            name='above_content_image_link',
            field=models.URLField(blank=True, help_text='The link for the image displayed above content', verbose_name='above content image link'),
        ),
        migrations.AddField(
            model_name='page',
            name='above_content_target',
            field=models.CharField(blank=True, help_text='The target (ie "_blank" for the link for the image displayed above content', max_length=20, verbose_name='above content target'),
        ),
        migrations.AddField(
            model_name='page',
            name='below_content_image_link',
            field=models.URLField(blank=True, help_text='The link for the image displayed below content', verbose_name='below content image link'),
        ),
        migrations.AddField(
            model_name='page',
            name='below_content_target',
            field=models.CharField(blank=True, help_text='The target (ie "_blank" for the link for the image displayed below content', max_length=20, verbose_name='below content target'),
        ),
        migrations.AddField(
            model_name='post',
            name='above_content_image_link',
            field=models.URLField(blank=True, help_text='The link for the image displayed above content', verbose_name='above content image link'),
        ),
        migrations.AddField(
            model_name='post',
            name='above_content_target',
            field=models.CharField(blank=True, help_text='The target (ie "_blank" for the link for the image displayed above content', max_length=20, verbose_name='above content target'),
        ),
        migrations.AddField(
            model_name='post',
            name='below_content_image_link',
            field=models.URLField(blank=True, help_text='The link for the image displayed below content', verbose_name='below content image link'),
        ),
        migrations.AddField(
            model_name='post',
            name='below_content_target',
            field=models.CharField(blank=True, help_text='The target (ie "_blank" for the link for the image displayed below content', max_length=20, verbose_name='below content target'),
        ),
    ]
