# Generated by Django 4.2 on 2023-04-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougblog', '0013_event_above_content_image_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='above_content_target',
        ),
        migrations.RemoveField(
            model_name='event',
            name='below_content_target',
        ),
        migrations.RemoveField(
            model_name='page',
            name='above_content_target',
        ),
        migrations.RemoveField(
            model_name='page',
            name='below_content_target',
        ),
        migrations.RemoveField(
            model_name='post',
            name='above_content_target',
        ),
        migrations.RemoveField(
            model_name='post',
            name='below_content_target',
        ),
        migrations.AddField(
            model_name='event',
            name='above_content_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie "_blank" for the link for the image displayed above content', max_length=70, verbose_name='above content attributes'),
        ),
        migrations.AddField(
            model_name='event',
            name='below_content_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie "_blank" for the link for the image displayed below content', max_length=70, verbose_name='below content attributes'),
        ),
        migrations.AddField(
            model_name='page',
            name='above_content_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie "_blank" for the link for the image displayed above content', max_length=70, verbose_name='above content attributes'),
        ),
        migrations.AddField(
            model_name='page',
            name='below_content_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie "_blank" for the link for the image displayed below content', max_length=70, verbose_name='below content attributes'),
        ),
        migrations.AddField(
            model_name='post',
            name='above_content_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie "_blank" for the link for the image displayed above content', max_length=70, verbose_name='above content attributes'),
        ),
        migrations.AddField(
            model_name='post',
            name='below_content_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie "_blank" for the link for the image displayed below content', max_length=70, verbose_name='below content attributes'),
        ),
    ]
