# Generated by Django 4.1.7 on 2023-04-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0013_alter_placement_options_remove_placement_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_image_link',
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_format',
            field=models.CharField(choices=[('same', 'same as content'), ('markdown', 'markdown'), ('html', 'html')], default='same', help_text='The format (or markup method) used for the summary', max_length=20, verbose_name='summary format'),
        ),
    ]
