# Generated by Django 4.1.7 on 2023-04-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0014_remove_post_title_image_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='whenday',
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whenday', models.DateField(help_text='The date of the event', verbose_name='date')),
                ('event', models.ForeignKey(help_text='The event to which this date belongs', on_delete=django.db.models.deletion.CASCADE, to='sdchomepage.event')),
            ],
            options={
                'ordering': ('-whenday',),
            },
        ),
    ]
