# Generated by Django 4.2 on 2023-04-16 10:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tougblog', '0015_remove_event_above_content_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sortable_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='The date/time this therad was created', null=True, verbose_name='sortable date'),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The user who created ths thread', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
