# Generated by Django 4.1.7 on 2023-04-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0015_alter_event_options_remove_event_whenday_eventdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title_image_link',
        ),
    ]
