# Generated by Django 4.1.7 on 2023-04-08 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdchomepage', '0016_remove_event_title_image_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['starttime', 'lenmin']},
        ),
        migrations.AlterModelOptions(
            name='eventdate',
            options={'ordering': ('whenday', 'event')},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The user who created ths thread', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the thread', max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(help_text='The code that provides a character based ID for this page')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this therad was created', verbose_name='created')),
                ('content_format', models.CharField(choices=[('markdown', 'markdown'), ('html', 'html')], default='markdown', help_text='The format (or markup method) used for the content', max_length=20, verbose_name='content format')),
                ('content', models.TextField(blank=True, help_text='The content of the post', verbose_name='content')),
                ('list_order', models.CharField(blank=True, default='~', help_text='A character to determine the place on the list. Numbers are higher than capital letters, which are higher than small letters', max_length=1)),
                ('author', models.ForeignKey(blank=True, help_text='The user who created ths thread', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('title_image', models.ForeignKey(blank=True, help_text='The image to display above the title, and to use for social media graphs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdchomepage.image')),
            ],
            options={
                'ordering': ('list_order', '-created'),
            },
        ),
    ]
