# Generated by Django 4.1.7 on 2023-04-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0017_alter_event_options_alter_eventdate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='The code that provides a character based ID for this page', unique=True),
        ),
    ]
