# Generated by Django 4.1.7 on 2023-04-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0018_alter_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_author_flag',
            field=models.BooleanField(default=True, help_text='Flag indicating if the author should be shown.  This is just a flag - the template has to be coded appropriately for this to work', verbose_name='show_author'),
        ),
        migrations.AddField(
            model_name='post',
            name='show_created_flag',
            field=models.BooleanField(default=True, help_text='Flag indicating if the creation date should be shown.  This is just a flag - the template has to be coded appropriately for this to work', verbose_name='show_created'),
        ),
    ]
