# Generated by Django 4.2 on 2023-04-17 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tougblog', '0018_alter_post_options_remove_post_list_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, help_text='The URL.  This will be overwritten if a file is uploaded', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The user who uploaded this image', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time this image was created', verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, help_text='The file to be uploaded - can be blank if URL is entered and no file needs to be uploaded', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(help_text='The title of the image', max_length=100, verbose_name='Title'),
        ),
    ]
