# Generated by Django 4.2 on 2023-04-16 10:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    Post = apps.get_model("tougblog", "Image")
    db_alias = schema_editor.connection.alias
    for image in Post.objects.using(db_alias):
        if not image.url > '':
            image.url = image.file.url
        image.file = None
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tougblog', '0019_image_url_alter_image_author_alter_image_created_and_more')
    ]

