# Generated by Django 4.1.7 on 2023-04-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdchomepage', '0019_post_show_author_flag_post_show_created_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='show_author_flag',
            new_name='show_author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='show_created_flag',
            new_name='show_created',
        ),
    ]
