# Generated by Django 4.2 on 2023-04-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougblog', '0020_image_url_update _url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, help_text='The file to be uploaded - can be blank if URL is entered and no file needs to be uploaded - Is removed once saved', null=True, upload_to='gallery/'),
        ),
    ]
